/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForumIndexRouteImport } from './routes/forum/index'
import { Route as ForumTopicSlugRouteImport } from './routes/forum/topic/$slug'
import { Route as ForumCategorySlugRouteImport } from './routes/forum/category/$slug'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumIndexRoute = ForumIndexRouteImport.update({
  id: '/forum/',
  path: '/forum/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumTopicSlugRoute = ForumTopicSlugRouteImport.update({
  id: '/forum/topic/$slug',
  path: '/forum/topic/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumCategorySlugRoute = ForumCategorySlugRouteImport.update({
  id: '/forum/category/$slug',
  path: '/forum/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/forum/': typeof ForumIndexRoute
  '/forum/category/$slug': typeof ForumCategorySlugRoute
  '/forum/topic/$slug': typeof ForumTopicSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/forum': typeof ForumIndexRoute
  '/forum/category/$slug': typeof ForumCategorySlugRoute
  '/forum/topic/$slug': typeof ForumTopicSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/forum/': typeof ForumIndexRoute
  '/forum/category/$slug': typeof ForumCategorySlugRoute
  '/forum/topic/$slug': typeof ForumTopicSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/forum/'
    | '/forum/category/$slug'
    | '/forum/topic/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/forum'
    | '/forum/category/$slug'
    | '/forum/topic/$slug'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/forum/'
    | '/forum/category/$slug'
    | '/forum/topic/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ForumIndexRoute: typeof ForumIndexRoute
  ForumCategorySlugRoute: typeof ForumCategorySlugRoute
  ForumTopicSlugRoute: typeof ForumTopicSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/': {
      id: '/forum/'
      path: '/forum'
      fullPath: '/forum/'
      preLoaderRoute: typeof ForumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/topic/$slug': {
      id: '/forum/topic/$slug'
      path: '/forum/topic/$slug'
      fullPath: '/forum/topic/$slug'
      preLoaderRoute: typeof ForumTopicSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/category/$slug': {
      id: '/forum/category/$slug'
      path: '/forum/category/$slug'
      fullPath: '/forum/category/$slug'
      preLoaderRoute: typeof ForumCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ForumIndexRoute: ForumIndexRoute,
  ForumCategorySlugRoute: ForumCategorySlugRoute,
  ForumTopicSlugRoute: ForumTopicSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
