import {zodResolver}from"@hookform/resolvers/zod";
import{Link,useNavigate}from"@tanstack/react-router";
import{ArrowRight,LoaderCircle,Lock,LogOut,Menu,MessageSquare,MessageSquareText,Pin,Play,Send,X}from"lucide-react";
import{motion}from"motion/react";
import{forwardRef,useId,useRef,useState}from"react";
import{useForm}from"react-hook-form";
import{z}from"zod";
import{COMING_SOON,createReply,createTopic,formatDate,slugify,supabase,useAuth,type Category,type Topic}from"./lib";

export function Reveal({children,className}:{children:React.ReactNode;className?:string}){return <motion.div className={className} initial={{opacity:0,y:26}} whileInView={{opacity:1,y:0}} viewport={{once:true,margin:"-70px"}} transition={{duration:.58,ease:[.22,1,.36,1]}}>{children}</motion.div>}
export const PlayDialog=forwardRef<HTMLDialogElement>(function PlayDialog(_,ref){const id=useId();return <dialog ref={ref} className="play-dialog" aria-labelledby={id}><div className="dialog-glow" aria-hidden/><form method="dialog"><button className="dialog-close" aria-label="Закрыть окно"><X aria-hidden/></button></form><img src="/images/brand/ncreate-logo.webp" width="260" height="260" alt="Логотип NCreate"/><p className="eyebrow">NCREATE</p><h2 id={id}>Начать играть</h2><p>{COMING_SOON}</p><dl className="dialog-details"><div><dt>IP</dt><dd>{COMING_SOON}</dd></div><div><dt>Версия</dt><dd>{COMING_SOON}</dd></div><div><dt>Лаунчер</dt><dd>{COMING_SOON}</dd></div></dl></dialog>});
function Header(){const[open,setOpen]=useState(false);const dialog=useRef<HTMLDialogElement>(null);const auth=useAuth();const play=()=>{setOpen(false);dialog.current?.showModal()};return <><header className="site-header"><div className="header-inner"><Link to="/" className="brand-link" aria-label="NCreate — главная"><img src="/images/brand/ncreate-logo-160.webp" width="52" height="52" alt=""/><span>NCreate</span></Link><nav className="desktop-nav" aria-label="Основная навигация"><a href="/#server">Сервер</a><Link to="/forum">Форум</Link><span className="nav-disabled" title={COMING_SOON}>Помощь</span><span className="nav-disabled" title={COMING_SOON}>Донат</span></nav><div className="header-actions">{auth.user?<button className="text-button" onClick={()=>void auth.logout()}><LogOut aria-hidden/>Выйти</button>:<Link to="/login" search={{redirect:"/forum"}} className="text-button">Войти</Link>}<button className="primary-button compact" onClick={play}><Play aria-hidden/>Начать играть</button></div><button className="menu-button" aria-expanded={open} aria-controls="mobile-menu" aria-label={open?"Закрыть меню":"Открыть меню"} onClick={()=>setOpen(v=>!v)}>{open?<X aria-hidden/>:<Menu aria-hidden/>}</button></div>{open?<nav className="mobile-menu" id="mobile-menu" aria-label="Мобильная навигация"><a href="/#server">Сервер</a><Link to="/forum">Форум</Link><span>Помощь <small>Скоро</small></span><span>Донат <small>Скоро</small></span>{auth.user?<button onClick={()=>void auth.logout()}>Выйти</button>:<Link to="/login" search={{redirect:"/forum"}}>Войти</Link>}<button className="primary-button" onClick={play}>Начать играть</button></nav>:null}</header><PlayDialog ref={dialog}/></>}
function Footer(){return <footer className="site-footer"><div className="footer-grid"><div className="footer-brand"><img src="/images/brand/ncreate-logo-160.webp" width="96" height="96" alt="Логотип NCreate" loading="lazy"/><div><strong>NCreate</strong><p>{COMING_SOON}</p></div></div><nav aria-label="Навигация в подвале"><a href="/#server">Сервер</a><Link to="/forum">Форум</Link><span>Помощь — скоро будет</span><span>Правовая информация — скоро будет</span></nav></div><div className="footer-bottom"><p>© {new Date().getFullYear()} NCreate</p><p>НЕ ЯВЛЯЕТСЯ ОФИЦИАЛЬНЫМ ПРОДУКТОМ MINECRAFT. НЕ ОДОБРЕНО И НЕ СВЯЗАНО С MOJANG ИЛИ MICROSOFT.</p></div><img className="footer-panorama" src="/images/ncreate/ncreate-image-09.webp" srcSet="/images/ncreate/ncreate-image-09-480.webp 480w, /images/ncreate/ncreate-image-09-640.webp 640w, /images/ncreate/ncreate-image-09-840.webp 840w, /images/ncreate/ncreate-image-09.webp 1448w" sizes="(max-width: 820px) 100vw, 1448px" width="1448" height="526" loading="lazy" alt="Пиксельная панорама NCreate с блоками, растениями и водой"/></footer>}
export function SiteShell({children}:{children:React.ReactNode}){return <div className="site-shell"><Header/><main>{children}</main><Footer/></div>}

const login=z.object({email:z.string().trim().email("Введите корректный email"),password:z.string().min(1,"Введите пароль")});const registration=login.extend({username:z.string().trim().min(3,"Минимум 3 символа").max(32,"Не более 32 символов").regex(/^[A-Za-z0-9_.-]+$/,"Только латиница, цифры, точка, дефис и подчёркивание"),password:z.string().min(8,"Минимум 8 символов")});type AuthValues=z.infer<typeof registration>;
export function AuthForm({mode,redirect="/forum"}:{mode:"login"|"register";redirect?:string}){const navigate=useNavigate();const signup=mode==="register";const[error,setError]=useState("");const form=useForm<AuthValues>({resolver:zodResolver(registration),defaultValues:{username:signup?"":"login-user",email:"",password:""},mode:"onBlur"});const submit=form.handleSubmit(async v=>{setError("");try{if(signup){const{data}=await supabase.from("profiles").select("id").ilike("username",v.username).limit(1);if(data?.length)throw new Error("Это имя пользователя уже занято");const{error:e}=await supabase.functions.invoke("register-account",{body:v});if(e)throw new Error("Не удалось создать аккаунт. Попробуйте позже")}const{error:e}=await supabase.auth.signInWithPassword(v);if(e)throw new Error("Не удалось войти. Проверьте email и пароль.");window.location.assign(redirect.startsWith("/")?redirect:"/forum");await navigate({to:"/forum"})}catch(e){setError(e instanceof Error?e.message:"Не удалось выполнить запрос")}});return <form className="auth-form" onSubmit={submit} noValidate>{error?<div className="form-alert" role="alert">{error}</div>:null}{signup?<label className="form-field"><span>Имя пользователя</span><input autoComplete="username" aria-invalid={!!form.formState.errors.username}{...form.register("username")}/><small>{form.formState.errors.username?.message??"Латиница, цифры, точка, дефис или подчёркивание"}</small></label>:null}<label className="form-field"><span>Email</span><input type="email" autoComplete="email" aria-invalid={!!form.formState.errors.email}{...form.register("email")}/><small>{form.formState.errors.email?.message}</small></label><label className="form-field"><span>Пароль</span><input type="password" autoComplete={signup?"new-password":"current-password"} aria-invalid={!!form.formState.errors.password}{...form.register("password")}/><small>{form.formState.errors.password?.message}</small></label><button className="primary-button full-button" disabled={form.formState.isSubmitting}>{form.formState.isSubmitting?<LoaderCircle className="spin" aria-hidden/>:<ArrowRight aria-hidden/>}{signup?"Создать аккаунт":"Войти"}</button><p className="auth-switch">{signup?"Уже есть аккаунт?":"Нет аккаунта?"} <Link to={signup?"/login":"/register"}>{signup?"Войти":"Регистрация"}</Link></p></form>}

export function ForumShell({title,subtitle,categories,children}:{title:string;subtitle?:string;categories:Category[];children:React.ReactNode}){return <SiteShell><section className="forum-hero"><div><p className="eyebrow">СООБЩЕСТВО NCREATE</p><h1>{title}</h1><p>{subtitle??COMING_SOON}</p></div><MessageSquareText aria-hidden/></section><nav className="forum-breadcrumbs" aria-label="Хлебные крошки"><Link to="/forum">Форум</Link></nav><section className="forum-content"><div className="forum-layout"><aside className="category-panel"><div className="panel-title">Категории <strong>{categories.length}</strong></div>{categories.length?categories.map(c=><Link key={c.id} to="/forum/category/$slug" params={{slug:c.slug}}><MessageSquareText aria-hidden/><div><strong>{c.name}</strong><small>{c.description??COMING_SOON}</small></div><span>›</span></Link>):<div className="mini-empty">Категории появятся позже</div>}</aside><div className="forum-main">{children}</div></div></section></SiteShell>}
export function TopicList({topics}:{topics:Topic[]}){if(!topics.length)return <div className="empty-state"><span>0</span><h2>Тем пока нет</h2><p>{COMING_SOON}</p></div>;return <div className="topic-list">{topics.map(t=><Link className="topic-row" to="/forum/topic/$slug" params={{slug:t.slug}} key={t.id}><span className="topic-icon"><MessageSquare aria-hidden/></span><div className="topic-main"><div className="topic-flags">{t.is_pinned?<Pin aria-label="Закреплено"/>:null}{t.is_locked?<Lock aria-label="Закрыто"/>:null}</div><h2>{t.title}</h2><p>{t.author_name} · {formatDate(t.created_at)}</p></div><strong>{t.reply_count}<small>ответов</small></strong></Link>)}</div>}
const topicSchema=z.object({title:z.string().trim().min(3,"Минимум 3 символа").max(120),body:z.string().trim().min(3,"Минимум 3 символа").max(20000)});type TopicValues=z.infer<typeof topicSchema>;
export function TopicForm({categoryId}:{categoryId:number}){const[error,setError]=useState("");const form=useForm<TopicValues>({resolver:zodResolver(topicSchema),defaultValues:{title:"",body:""}});const submit=form.handleSubmit(async v=>{setError("");try{const slug=slugify(v.title);await createTopic(categoryId,v.title,slug,v.body);window.location.assign(`/forum/topic/${slug}`)}catch(e){setError(e instanceof Error?e.message:"Не удалось создать тему")}});return <form className="forum-form" onSubmit={submit} noValidate><h2>Новая тема</h2>{error?<div className="form-alert" role="alert">{error}</div>:null}<label>Заголовок<input {...form.register("title")}/><small>{form.formState.errors.title?.message}</small></label><label>Сообщение<textarea rows={7}{...form.register("body")}/><small>{form.formState.errors.body?.message}</small></label><button className="primary-button" disabled={form.formState.isSubmitting}><Send aria-hidden/>Создать тему</button></form>}
const replySchema=z.object({body:z.string().trim().min(2,"Минимум 2 символа").max(20000)});type ReplyValues=z.infer<typeof replySchema>;
export function ReplyForm({topicId,onCreated}:{topicId:string;onCreated:()=>Promise<void>}){const[error,setError]=useState("");const form=useForm<ReplyValues>({resolver:zodResolver(replySchema),defaultValues:{body:""}});const submit=form.handleSubmit(async v=>{setError("");try{await createReply(topicId,v.body);form.reset();await onCreated()}catch(e){setError(e instanceof Error?e.message:"Не удалось отправить ответ")}});return <form className="forum-form reply-form" onSubmit={submit}><h2>Ответить</h2>{error?<div className="form-alert" role="alert">{error}</div>:null}<label><span className="sr-only">Сообщение</span><textarea rows={6} placeholder="Напишите сообщение" {...form.register("body")}/><small>{form.formState.errors.body?.message}</small></label><button className="primary-button" disabled={form.formState.isSubmitting}><Send aria-hidden/>Отправить</button></form>}
