-- NCreate platform. Additive only; do not modify existing NCEA tables.
-- Apply only to Supabase project bualqaeinwifoopzflbt in organization NCEA.

create table public.ncreate_site_settings (
  site_id text primary key default 'ncreate',
  server_name text not null default 'NCreate',
  hero_title text not null default 'Создавай. Развивай. Играй в NCreate.',
  hero_subtitle text,
  server_ip text,
  minecraft_version text,
  online_players integer not null default 0,
  record_players integer not null default 0,
  total_players integer not null default 0,
  discord_url text,
  telegram_url text,
  youtube_url text,
  vk_url text,
  donate_url text,
  launcher_url text,
  status text not null default 'coming_soon',
  updated_at timestamptz not null default now(),
  constraint ncreate_site_settings_site_check check (site_id = 'ncreate'),
  constraint ncreate_site_settings_server_name_check check (
    server_name = btrim(server_name) and char_length(server_name) between 1 and 80
  ),
  constraint ncreate_site_settings_hero_title_check check (
    hero_title = btrim(hero_title) and char_length(hero_title) between 1 and 180
  ),
  constraint ncreate_site_settings_hero_subtitle_check check (
    hero_subtitle is null or char_length(hero_subtitle) between 1 and 280
  ),
  constraint ncreate_site_settings_counts_check check (
    online_players >= 0 and record_players >= 0 and total_players >= 0
  ),
  constraint ncreate_site_settings_status_check check (
    status in ('coming_soon', 'online', 'offline', 'maintenance')
  ),
  constraint ncreate_site_settings_discord_url_check check (
    discord_url is null or discord_url ~ '^https://[^[:space:]<>"''`]+$'
  ),
  constraint ncreate_site_settings_telegram_url_check check (
    telegram_url is null or telegram_url ~ '^https://[^[:space:]<>"''`]+$'
  ),
  constraint ncreate_site_settings_youtube_url_check check (
    youtube_url is null or youtube_url ~ '^https://[^[:space:]<>"''`]+$'
  ),
  constraint ncreate_site_settings_vk_url_check check (
    vk_url is null or vk_url ~ '^https://[^[:space:]<>"''`]+$'
  ),
  constraint ncreate_site_settings_donate_url_check check (
    donate_url is null or donate_url ~ '^https://[^[:space:]<>"''`]+$'
  ),
  constraint ncreate_site_settings_launcher_url_check check (
    launcher_url is null or launcher_url ~ '^https://[^[:space:]<>"''`]+$'
  )
);

comment on table public.ncreate_site_settings is
  'Public NCreate configuration. Unknown values stay NULL or zero; admin/owner writes only.';

create table public.ncreate_home_sections (
  id bigint generated by default as identity primary key,
  section_key text not null unique,
  title text,
  subtitle text,
  sort_order integer not null default 0,
  is_published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ncreate_home_sections_key_check check (
    section_key ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'
  ),
  constraint ncreate_home_sections_title_check check (
    title is null or char_length(title) between 1 and 180
  ),
  constraint ncreate_home_sections_subtitle_check check (
    subtitle is null or char_length(subtitle) between 1 and 500
  )
);

create table public.ncreate_home_cards (
  id bigint generated by default as identity primary key,
  section_id bigint not null references public.ncreate_home_sections(id) on delete cascade,
  title text not null default 'Скоро будет',
  description text,
  image_url text,
  sort_order integer not null default 0,
  is_published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ncreate_home_cards_title_check check (
    title = btrim(title) and char_length(title) between 1 and 180
  ),
  constraint ncreate_home_cards_description_check check (
    description is null or char_length(description) between 1 and 1000
  ),
  constraint ncreate_home_cards_image_url_check check (
    image_url is null or image_url ~ '^https://[^[:space:]<>"''`]+$'
  )
);

create table public.ncreate_forum_categories (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  description text,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ncreate_forum_categories_slug_check check (
    slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'
  ),
  constraint ncreate_forum_categories_name_check check (
    name = btrim(name) and char_length(name) between 1 and 80
  ),
  constraint ncreate_forum_categories_description_check check (
    description is null or char_length(description) between 1 and 280
  )
);

create table public.ncreate_forum_topics (
  id uuid primary key default gen_random_uuid(),
  category_id bigint not null references public.ncreate_forum_categories(id) on delete restrict,
  author_id uuid not null references public.profiles(id) on delete restrict,
  title text not null,
  slug text not null unique,
  is_pinned boolean not null default false,
  is_locked boolean not null default false,
  deleted_at timestamptz,
  deleted_by uuid references public.profiles(id) on delete restrict,
  deletion_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ncreate_forum_topics_title_check check (
    title = btrim(title) and char_length(title) between 3 and 180
  ),
  constraint ncreate_forum_topics_slug_check check (
    slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*-[0-9a-f]{8}$'
  ),
  constraint ncreate_forum_topics_deleted_check check (
    (deleted_at is null and deleted_by is null and deletion_reason is null)
    or (deleted_at is not null and deleted_by is not null)
  ),
  constraint ncreate_forum_topics_reason_check check (
    deletion_reason is null or char_length(deletion_reason) <= 500
  )
);

create table public.ncreate_forum_posts (
  id uuid primary key default gen_random_uuid(),
  topic_id uuid not null references public.ncreate_forum_topics(id) on delete cascade,
  author_id uuid not null references public.profiles(id) on delete restrict,
  body text not null,
  deleted_at timestamptz,
  deleted_by uuid references public.profiles(id) on delete restrict,
  deletion_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ncreate_forum_posts_body_check check (
    body = btrim(body) and char_length(body) between 1 and 20000
  ),
  constraint ncreate_forum_posts_deleted_check check (
    (deleted_at is null and deleted_by is null and deletion_reason is null)
    or (deleted_at is not null and deleted_by is not null)
  ),
  constraint ncreate_forum_posts_reason_check check (
    deletion_reason is null or char_length(deletion_reason) <= 500
  )
);

create index ncreate_home_sections_published_sort_idx
  on public.ncreate_home_sections (is_published, sort_order, id);
create index ncreate_home_cards_section_published_sort_idx
  on public.ncreate_home_cards (section_id, is_published, sort_order, id);
create index ncreate_forum_categories_active_sort_idx
  on public.ncreate_forum_categories (is_active, sort_order, id);
create index ncreate_forum_topics_category_active_created_idx
  on public.ncreate_forum_topics (category_id, is_pinned desc, created_at desc, id)
  where deleted_at is null;
create index ncreate_forum_topics_author_created_idx
  on public.ncreate_forum_topics (author_id, created_at desc);
create index ncreate_forum_topics_deleted_by_idx
  on public.ncreate_forum_topics (deleted_by) where deleted_by is not null;
create index ncreate_forum_posts_topic_active_created_idx
  on public.ncreate_forum_posts (topic_id, created_at, id)
  where deleted_at is null;
create index ncreate_forum_posts_author_created_idx
  on public.ncreate_forum_posts (author_id, created_at desc);
create index ncreate_forum_posts_deleted_by_idx
  on public.ncreate_forum_posts (deleted_by) where deleted_by is not null;

create or replace function private.ncreate_set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function private.ncreate_protect_topic_fields()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if (select auth.uid()) is not null
    and not private.is_staff((select auth.uid()))
    and (
      new.category_id is distinct from old.category_id
      or new.author_id is distinct from old.author_id
      or new.slug is distinct from old.slug
      or new.is_pinned is distinct from old.is_pinned
      or new.is_locked is distinct from old.is_locked
      or new.deleted_at is distinct from old.deleted_at
      or new.deleted_by is distinct from old.deleted_by
      or new.deletion_reason is distinct from old.deletion_reason
    )
  then
    raise exception 'Only NCreate staff can change topic moderation fields'
      using errcode = '42501';
  end if;
  return new;
end;
$$;

create or replace function private.ncreate_protect_post_fields()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if (select auth.uid()) is not null
    and not private.is_staff((select auth.uid()))
    and (
      new.topic_id is distinct from old.topic_id
      or new.author_id is distinct from old.author_id
      or new.deleted_at is distinct from old.deleted_at
      or new.deleted_by is distinct from old.deleted_by
      or new.deletion_reason is distinct from old.deletion_reason
    )
  then
    raise exception 'Only NCreate staff can change post moderation fields'
      using errcode = '42501';
  end if;
  return new;
end;
$$;

revoke all on function private.ncreate_set_updated_at() from public, anon, authenticated;
revoke all on function private.ncreate_protect_topic_fields() from public, anon, authenticated;
revoke all on function private.ncreate_protect_post_fields() from public, anon, authenticated;

create trigger ncreate_site_settings_set_updated_at
  before update on public.ncreate_site_settings
  for each row execute function private.ncreate_set_updated_at();
create trigger ncreate_home_sections_set_updated_at
  before update on public.ncreate_home_sections
  for each row execute function private.ncreate_set_updated_at();
create trigger ncreate_home_cards_set_updated_at
  before update on public.ncreate_home_cards
  for each row execute function private.ncreate_set_updated_at();
create trigger ncreate_forum_categories_set_updated_at
  before update on public.ncreate_forum_categories
  for each row execute function private.ncreate_set_updated_at();
create trigger ncreate_forum_topics_set_updated_at
  before update on public.ncreate_forum_topics
  for each row execute function private.ncreate_set_updated_at();
create trigger ncreate_forum_topics_protect_fields
  before update on public.ncreate_forum_topics
  for each row execute function private.ncreate_protect_topic_fields();
create trigger ncreate_forum_posts_set_updated_at
  before update on public.ncreate_forum_posts
  for each row execute function private.ncreate_set_updated_at();
create trigger ncreate_forum_posts_protect_fields
  before update on public.ncreate_forum_posts
  for each row execute function private.ncreate_protect_post_fields();

alter table public.ncreate_site_settings enable row level security;
alter table public.ncreate_home_sections enable row level security;
alter table public.ncreate_home_cards enable row level security;
alter table public.ncreate_forum_categories enable row level security;
alter table public.ncreate_forum_topics enable row level security;
alter table public.ncreate_forum_posts enable row level security;

grant select on public.ncreate_site_settings to anon, authenticated;
grant update on public.ncreate_site_settings to authenticated;

grant select on public.ncreate_home_sections, public.ncreate_home_cards to anon;
grant select, insert, update, delete on public.ncreate_home_sections,
  public.ncreate_home_cards to authenticated;
grant usage, select on sequence public.ncreate_home_sections_id_seq,
  public.ncreate_home_cards_id_seq to authenticated;

grant select on public.ncreate_forum_categories, public.ncreate_forum_topics,
  public.ncreate_forum_posts to anon;
grant select, insert, update on public.ncreate_forum_categories,
  public.ncreate_forum_topics, public.ncreate_forum_posts to authenticated;
grant delete on public.ncreate_forum_categories to authenticated;
grant usage, select on sequence public.ncreate_forum_categories_id_seq to authenticated;

create policy ncreate_site_settings_public_read on public.ncreate_site_settings
  for select to anon, authenticated using (site_id = 'ncreate');
create policy ncreate_site_settings_admin_update on public.ncreate_site_settings
  for update to authenticated
  using (private.is_admin((select auth.uid())))
  with check (site_id = 'ncreate' and private.is_admin((select auth.uid())));

create policy ncreate_home_sections_public_read on public.ncreate_home_sections
  for select to anon, authenticated using (is_published);
create policy ncreate_home_sections_staff_read on public.ncreate_home_sections
  for select to authenticated using (private.is_staff((select auth.uid())));
create policy ncreate_home_sections_admin_insert on public.ncreate_home_sections
  for insert to authenticated with check (private.is_admin((select auth.uid())));
create policy ncreate_home_sections_admin_update on public.ncreate_home_sections
  for update to authenticated
  using (private.is_admin((select auth.uid())))
  with check (private.is_admin((select auth.uid())));
create policy ncreate_home_sections_admin_delete on public.ncreate_home_sections
  for delete to authenticated using (private.is_admin((select auth.uid())));

create policy ncreate_home_cards_public_read on public.ncreate_home_cards
  for select to anon, authenticated using (
    is_published and exists (
      select 1 from public.ncreate_home_sections as section
      where section.id = section_id and section.is_published
    )
  );
create policy ncreate_home_cards_staff_read on public.ncreate_home_cards
  for select to authenticated using (private.is_staff((select auth.uid())));
create policy ncreate_home_cards_admin_insert on public.ncreate_home_cards
  for insert to authenticated with check (private.is_admin((select auth.uid())));
create policy ncreate_home_cards_admin_update on public.ncreate_home_cards
  for update to authenticated
  using (private.is_admin((select auth.uid())))
  with check (private.is_admin((select auth.uid())));
create policy ncreate_home_cards_admin_delete on public.ncreate_home_cards
  for delete to authenticated using (private.is_admin((select auth.uid())));

create policy ncreate_forum_categories_public_read on public.ncreate_forum_categories
  for select to anon, authenticated using (is_active);
create policy ncreate_forum_categories_staff_read on public.ncreate_forum_categories
  for select to authenticated using (private.is_staff((select auth.uid())));
create policy ncreate_forum_categories_admin_insert on public.ncreate_forum_categories
  for insert to authenticated with check (private.is_admin((select auth.uid())));
create policy ncreate_forum_categories_admin_update on public.ncreate_forum_categories
  for update to authenticated
  using (private.is_admin((select auth.uid())))
  with check (private.is_admin((select auth.uid())));
create policy ncreate_forum_categories_admin_delete on public.ncreate_forum_categories
  for delete to authenticated using (private.is_admin((select auth.uid())));

create policy ncreate_forum_topics_public_read on public.ncreate_forum_topics
  for select to anon using (
    deleted_at is null and exists (
      select 1 from public.ncreate_forum_categories as category
      where category.id = category_id and category.is_active
    )
  );
create policy ncreate_forum_topics_authenticated_read on public.ncreate_forum_topics
  for select to authenticated using (
    private.is_staff((select auth.uid()))
    or (
      deleted_at is null and exists (
        select 1 from public.ncreate_forum_categories as category
        where category.id = category_id and category.is_active
      )
    )
  );
create policy ncreate_forum_topics_user_insert on public.ncreate_forum_topics
  for insert to authenticated with check (
    author_id = (select auth.uid())
    and not is_pinned
    and not is_locked
    and deleted_at is null
    and deleted_by is null
    and exists (
      select 1 from public.ncreate_forum_categories as category
      where category.id = category_id and category.is_active
    )
  );
create policy ncreate_forum_topics_owner_update on public.ncreate_forum_topics
  for update to authenticated
  using (
    author_id = (select auth.uid()) and not is_locked and deleted_at is null
  )
  with check (
    author_id = (select auth.uid())
    and not is_locked
    and not is_pinned
    and deleted_at is null
    and deleted_by is null
    and exists (
      select 1 from public.ncreate_forum_categories as category
      where category.id = category_id and category.is_active
    )
  );
create policy ncreate_forum_topics_staff_update on public.ncreate_forum_topics
  for update to authenticated
  using (private.is_staff((select auth.uid())))
  with check (private.is_staff((select auth.uid())));

create policy ncreate_forum_posts_public_read on public.ncreate_forum_posts
  for select to anon using (
    deleted_at is null and exists (
      select 1
      from public.ncreate_forum_topics as topic
      join public.ncreate_forum_categories as category on category.id = topic.category_id
      where topic.id = topic_id and topic.deleted_at is null and category.is_active
    )
  );
create policy ncreate_forum_posts_authenticated_read on public.ncreate_forum_posts
  for select to authenticated using (
    private.is_staff((select auth.uid()))
    or (
      deleted_at is null and exists (
        select 1
        from public.ncreate_forum_topics as topic
        join public.ncreate_forum_categories as category on category.id = topic.category_id
        where topic.id = topic_id and topic.deleted_at is null and category.is_active
      )
    )
  );
create policy ncreate_forum_posts_user_insert on public.ncreate_forum_posts
  for insert to authenticated with check (
    author_id = (select auth.uid())
    and deleted_at is null
    and deleted_by is null
    and exists (
      select 1
      from public.ncreate_forum_topics as topic
      join public.ncreate_forum_categories as category on category.id = topic.category_id
      where topic.id = topic_id
        and topic.deleted_at is null
        and not topic.is_locked
        and category.is_active
    )
  );
create policy ncreate_forum_posts_owner_update on public.ncreate_forum_posts
  for update to authenticated
  using (
    author_id = (select auth.uid())
    and deleted_at is null
    and exists (
      select 1 from public.ncreate_forum_topics as topic
      where topic.id = topic_id and topic.deleted_at is null and not topic.is_locked
    )
  )
  with check (
    author_id = (select auth.uid())
    and deleted_at is null
    and deleted_by is null
  );
create policy ncreate_forum_posts_staff_update on public.ncreate_forum_posts
  for update to authenticated
  using (private.is_staff((select auth.uid())))
  with check (private.is_staff((select auth.uid())));

create or replace function public.create_ncreate_forum_topic(
  _category_id bigint,
  _title text,
  _slug text,
  _body text
)
returns uuid
language plpgsql
security invoker
set search_path = ''
as $$
declare
  created_topic_id uuid;
begin
  if (select auth.uid()) is null then
    raise exception 'authentication_required' using errcode = '42501';
  end if;
  if char_length(btrim(_title)) not between 3 and 180 then
    raise exception 'invalid_topic_title' using errcode = '22023';
  end if;
  if char_length(btrim(_body)) not between 1 and 20000 then
    raise exception 'invalid_topic_body' using errcode = '22023';
  end if;
  if _slug !~ '^[a-z0-9]+(?:-[a-z0-9]+)*-[0-9a-f]{8}$' then
    raise exception 'invalid_topic_slug' using errcode = '22023';
  end if;

  insert into public.ncreate_forum_topics (category_id, author_id, title, slug)
  values (_category_id, (select auth.uid()), btrim(_title), _slug)
  returning id into created_topic_id;

  insert into public.ncreate_forum_posts (topic_id, author_id, body)
  values (created_topic_id, (select auth.uid()), btrim(_body));

  return created_topic_id;
end;
$$;

create or replace function public.create_ncreate_forum_reply(_topic_id uuid, _body text)
returns uuid
language plpgsql
security invoker
set search_path = ''
as $$
declare
  created_post_id uuid;
begin
  if (select auth.uid()) is null then
    raise exception 'authentication_required' using errcode = '42501';
  end if;
  if char_length(btrim(_body)) not between 1 and 20000 then
    raise exception 'invalid_reply_body' using errcode = '22023';
  end if;

  insert into public.ncreate_forum_posts (topic_id, author_id, body)
  values (_topic_id, (select auth.uid()), btrim(_body))
  returning id into created_post_id;

  return created_post_id;
end;
$$;

revoke all on function public.create_ncreate_forum_topic(bigint, text, text, text)
  from public, anon;
revoke all on function public.create_ncreate_forum_reply(uuid, text)
  from public, anon;
grant execute on function public.create_ncreate_forum_topic(bigint, text, text, text)
  to authenticated;
grant execute on function public.create_ncreate_forum_reply(uuid, text)
  to authenticated;

insert into public.ncreate_site_settings (
  site_id,
  server_name,
  hero_title,
  hero_subtitle,
  online_players,
  record_players,
  total_players,
  status
)
values (
  'ncreate',
  'NCreate',
  'Создавай. Развивай. Играй в NCreate.',
  'Скоро будет',
  0,
  0,
  0,
  'coming_soon'
);
